version: 1
formatters:
  brief:
    format: "%(asctime)s - %(message)s"
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  thread:
    format: "%(asctime)s - %(filename)s[%(funcName)s:line:%(lineno)d] %(process)d:%(thread)d:%(threadName)s- %(levelname)s: %(message)s"
handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : INFO
    stream  : ext://sys.stdout
  file:
    class : logging.FileHandler
    formatter: thread
    level: DEBUG
    filename: ./log/webapp/flask/debug.log
    mode: w
  error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ./log/webapp/flask/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  main:
    level: DEBUG
root:
  level: DEBUG
  handlers: [file]